# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e5287995e1c3c7eda6792c73cdb3e27def6891b4e1381e0b89c6ab9265b03cb5237517b2a81f0a45d28a3122720083ec605e2e203627110f97b337f7cad4499

test:
  secret_key_base: 4868250c8c982970c27d943868db809ff1ef1b849b2168fde02941549a0dac910eade01dee425587edeb44f244094bd3058394b65e3b3b3b649035aa2d7fa731

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
